logging:
  level:
    root: INFO
    dev.nkucherenko.troubleshooting: DEBUG

masking:
  replaceList:
    - regex: "(name=')(.{1}).+?(')"
      replace: "$1$2***$3"

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,loggers,env,beans,prometheus